### ISSUE TITLE
Order affecté en fonction du type de stat

### ISSUE THREAD

**Issue by CCoruble** [CCoruble/DaD#10]
Pour l'instant lorsque l'on créé un Env, l'attribut "order" est passé en argument du constructeur. 

Afin d'éviter les bugs et rendre le tout plus "solide", est-ce qu'il ne serait pas mieux que l'attribut "order" soit déterminé à l'intérieur du constructeur en fonction du type de stat, SET / ADD / ...

De la même façon dans les fichiers de conf, AllHeroRaces.xml par exemple, ne faudrait-il pas enlever la valeur "order" afin qu'elle soit déterminé, une fois de plus, dans le constructeur ?

Éventuellement plus tard rajouter des types de stats pour avoir des ordres de calculs différents.

**Comment by Rivelia** [comment]
Si tu veux mais le problème est que tu ne pourras pas avoir des effets qui multiplient d'autres effets.

Par exemple si tu veux multiplier toutes les stats additives par un buff, tu ne pourra pas vu que tu ne pourras pas accéder à l'order.

Cela va considérablement réduire les capacités de créer des effets.

**Comment by CCoruble** [comment]
On ne peut pas palier à ça en créant d'autres effets justement ?
Par exemple un medium buff, avec un nom plus parlant, qui aura un order entre add et mutiply.

Mais de la façon où est faite la structure de Env, je ne vois pas comment juste avec l'ordre on peut, par exemple, multiplié seulement les Env de type "ADD" par 2. Cela prendra forcément en compte les Env qui ont un order inférieur à ceux de type ADD.

A moins de mettre une cible pour l'effet, ce qui rendrait la chose très complexe ?!

**Comment by Rivelia** [comment]
Justement si tu enleve l'order tu pourra pas multiplier en 0x50 par exemple.

Mais oui tu ne pourras pas explicitement multiplier les "add", par contre tu pourras tout multiplier, ou multiplier uniquement les stats de bases (0x10).

**Comment by CCoruble** [comment]
La solution de créer plusieurs type spéciaux d'effet ne fonctionnerait-elle pas ?
Bien que ça limiterait comme tu as dis les effets possibles, on pourrait tout de même en avoir une certaine quantité, tous connus à l'avance avec un order bien précis.

Ex: 
HIGH_MULTIPLY, order:50
HIGH_DIVIDE, order: 50
ULTIMATE_MULTIPLY, order:100
ULTIMATE_DIVIDE, order:100

**Comment by Rivelia** [comment]
n'empeche pas que ca va dans tout les cas reduire tes cas de possiblites. a chaque fois il va faloir que tu dev la stat et en plus la referencer dans tout ton code. alors que un order directement dans le XML n'a pas ce probleme et se detache completement du core

**Comment by CCoruble** [comment]
Du coup rajouter un constructeur qui, si l'on ne précise pas l'order en argument, mettra la valeur par défaut te parait être une bonne solution ? La valeur par défaut est indiqué dans le fichier "Env_order.txt".

Cela permettra de créer les Env "non spécial" plus simplement et éviter les erreurs.
Mais si l'on souhaite avoir un Env avec une valeur en particulier on pourra et cela n'impactera pas le système de calcul ou d'Env de manière général.

**Comment by Rivelia** [comment]
Oui si tu veux.

**Comment by CCoruble** [comment]
Mis en place dans le commit 7d2433636dc2ac85e9d7aba87e6c968057ebceec
