### ISSUE TITLE
Utilisation HashMap dans Holder

### ISSUE THREAD

**Issue by CCoruble** [CCoruble/DaD#3]
Tous les holder ont un attribut de type HashMap<Integer,{Monster\Item\dungeon}Template>.
L'Integer est utilisé pour récupérer un Template, néanmoins un ID est déjà présent dans chaque Template.

Ne serait-il pas mieux d'utiliser l'ID du Template? Bien que cela puisse augmenter légèrement le temps de traitement pour aller récupérer un Template.

Merci.

**Comment by Rivelia** [comment]
La perte de performances serait trop importante.

Par contre tu peux utiliser un TIntObjectMap à la place d'un HashMap, c'est plus optimisé.
Elle fait partie de la bibliothèque gnu.trove. Elle n'est pas inclue de base dans Java.

Documentation:
http://trove4j.sourceforge.net/javadocs/gnu/trove/map/TIntObjectMap.html

La bibliothèque:
https://bitbucket.org/trove4j/trove

**Comment by CCoruble** [comment]
Ok, je garde la HashMap, à voir peut-être plus tard changer vers TIntObjectMap.
