### ISSUE TITLE
Créer l'item gold.

### ISSUE THREAD

**Issue by CCoruble** [CCoruble/DaD#5]
Pour l'instant l'argent est un simple attribut double "gold". Il faudrait changer pour que ce soit un item avec un stack infinie.

**Comment by CCoruble** [comment]
Pour l'instant les items utilisés / générés dans le jeu ne sont que des items équipables.
Il faudra rajouter l'argent qui n'est pas un objet équipable et surement des potions plus tard.

_Des idées suggestions pour une structure de classe pour distinguer les différents items ?_
Je pensais à:
**1)**
Item - Gear [fille de item] (objets équipables armures / armes)
        - NonUsable [fille de item] (Pièces d'or, éventuellement des reliques de quêtes)
        - Usable [fille de item] (Potions et autres)
**2)**
Item - Gear [fille de item] (objets équipables armures / armes)
        - Goods [fille de item] (Tous le reste, potions, pièces d'or, ... )
Avec une interface "Usable" pour les effets d'utilisation des objets, qu'ils soient Gear ou Goods.

**Comment by CCoruble** [comment]
Solution 3, peut-être complexe mais respecterait la structure actuel du programme:
![image](https://user-images.githubusercontent.com/24699373/35857297-ff5f8b2e-0b38-11e8-89f6-91dd95e900dd.png)

**Comment by Rivelia** [comment]
ItemInstance suffira. Applique à cet ItemInstance un Handler que tu parsera via XML, par exemple si itemType = "Potion" tu creera le handler ayant comme nom de classe "PotionHandler".

**Comment by CCoruble** [comment]
J'ai du mal à voir comment mettre ça en place, si ce n'est un fichier avec des effets qui sont chargés au début. 
Chaque itemTemplate réfèrerait à un de ces effets et lorsque l'on souhaiterait utilisé un objet cela appliquerait l'effet lié.
Les effet seraient stockés dans un effectHolder et c'est un effectHandler qui appliquerait les effets lorsque le héro utiliserait l'objet.

Si ce n'est pas comme ça que tu le pensais, est-ce tu peux ré-expliquer en détail la façon dont tu le ferais ?

**Comment by Rivelia** [comment]
En gros:

Crée un package "handlers".
Dedans tu y met une classe abstraite "AbstractItemHandler".
Tu crée toutes tes classes qui vont extend de la classe abstraite "AbstractItemHandler" : PotionHandler, ScrollHandler, EquipmentHandler, MiscHandler...

**AbstractItemHandler aura:**
Constructeur:
AbstractItemHandler(Creature creature, ItemInstance item);
**Variables membres:**
private Creature _owner;
private ItemInstance _item;
**Méthodes:**
public abstract boolean use();
public final Creature getOwner()
public final ItemInstance getItem()
(surement d'autres méthodes mais ça me vient pas)

Chaque classes qui extend de AbstractItemHandler auront un override sur use() bien entendu.

Voilà quelques exemples pour les classes:

MiscHandler:
```
@Override
public boolean use()
{
  getOwner().sendMessage("This item is not useable");
  getOwner().sendActionFailed();
  return false;
}
```

PotionHandler:
```
@Override
public boolean use()
{
  ItemFunctions.removeItem(getOwner(), getItem(), 1); // Creature (owner),  ItemInstance (used item), long (quantity);
  getOwner().notifyPotionUsed();
  getItem().applyEffects();
  return true;
}
```

ScrollHandler:
```
@Override
public boolean use()
{
  if (LocationFunctions.isInsideMagicCircle(getOwner().getLocation()))
  {
    ItemFunctions.removeItem(getOwner(), getItem(), 1); // Creature (owner),  ItemInstance (used item), long (quantity);
    getOwner().notifyPotionUsed();
    getItem().applyEffects();
    return true;
  }
  getOwner().sendMessage("You are not inside a magic circle!");
  getOwner().sendActionFailed();
  return false;
}
```

Le booléen use() détermine si l'utilisation de l'item s'est bien passé et qu'il a été "handled".

Dans ton XML reader:
Tu lis le set ItemHandler.
Si il est != "None" tu load l'item en fonction du nom de classe en rajoutant "Handler" à la suite.
On appelle ça la "Reflection". Elle permet de créer des classes inconnues avec des constructeurs non connus lors de la compilation en byte-code par la JVM.

Tu dois stocker un item de type Class dans ton ItemTemplate:
`Class<?> clazz = Class.forName("mygamepackage.handlers." + handlerName + "Handler");`

Et lors de l'initialisation via une ItemInstance:
```
Constructor<?> constructor = getTemplate().clazz.getConstructor(Creature.class, ItemInstance.class);
AbstractItemHandler instance = (AbstractItemHandler) constructor.newInstance("creature", player, "item", this);
```

Dans ton XML:
à l'intérieur d'un `<item id="47" name="Gold">` tu met:
`<set name="ItemHandler" value="Misc" />`

**Comment by Rivelia** [comment]
Lorsque tu crée une nouvelle instance d'un handler n'oublie pas que certaines erreurs peuvent survenires:

La JVM ne trouve pas ou n'arrive pas à charger la classe
La classe que tu essayes d'instancier n'a pas le bon constructeur
Le constructor a throw une exception
Le constructeur que tu essaye d'invoquer n'est pas publique
Un module responsable de la sécurité a été installé et empêche la reflection de se produire

**Comment by CCoruble** [comment]
Dernière question:
Pour l'objet gold, quelle itemType est-ce (un nouveau évidemment) ? Quelle nom de balise ? (<gear> pour armures et armes pour l'instant)
